"""empty message

Revision ID: 14449430ba53
Revises: c0ddf6d9e169
Create Date: 2021-01-30 12:15:40.501321

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14449430ba53'
down_revision = 'c0ddf6d9e169'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'answer', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.add_column('question', sa.Column('modify_date', sa.DateTime(), nullable=True))
    op.create_foreign_key(None, 'question', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'question', type_='foreignkey')
    op.drop_column('question', 'modify_date')
    op.drop_constraint(None, 'answer', type_='foreignkey')
    # ### end Alembic commands ###
