"""empty message

Revision ID: 364445d0e729
Revises: eb0dd5d07ca1
Create Date: 2021-01-27 17:59:46.205985

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '364445d0e729'
down_revision = 'eb0dd5d07ca1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=150), nullable=False),
    sa.Column('password', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
