"""empty message

Revision ID: c0631c3cc09a
Revises: c438d923bccd
Create Date: 2021-01-28 10:27:46.075460

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c0631c3cc09a'
down_revision = 'c438d923bccd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answer', sa.Column('user_id', sa.Integer(), server_default='1', nullable=True))
    op.create_foreign_key(None, 'answer', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('question', 'user_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('question', 'user_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'answer', type_='foreignkey')
    op.drop_column('answer', 'user_id')
    # ### end Alembic commands ###
